### ISSUE TITLE
Issues importing HmIP Devices from debmatic

### ISSUE THREAD

**Issue by zech** [Zefau/ioBroker.jarvis#316]
**Versions**
- Which jarvis version are you running: 1.1.0-beta.77
- Please provide your `Support-ID` (in jarvis via Settings -> Help): No config issue so i doubt its required here.

**Describe the bug**
Clicking import devices and selecting only `HomeMatic / HomeMatic IP via CCU adapter` in `Search adapter structure for all devices` leads to a an error on the browser console and no devices are imported.

**Expected behavior**
HmIP devices should be imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/460040/98297322-8754fb80-1fb4-11eb-89ae-09812c73f9fd.png)

a.native is null/undefined so TYPE cannot be found.
![image](https://user-images.githubusercontent.com/460040/98297472-bf5c3e80-1fb4-11eb-860c-70879b6c79c3.png)

Maybe this is because I'm using debmatic instead of the genuine CCU3 here.

**Comment by Zefau** [comment]
This is a bug indeed because I'm expecting `native` (and `TYPE`). This is necessary to map the states, which are different for device types. 

Could you check if this applies to all your hm-rpc devices in ioBroker or maybe only a single one?

I will fix the bug, but you will not find any devices with the Importer if `TYPE` is not given.

**Comment by Zefau** [comment]
`v1.1.0-beta.78` should fix the error.

**Comment by zech** [comment]
I've narrowed it down to hm-rpc using the "old" `rfd` for HomeMatic none IP devices. Its missing the native object in the configuration object of `HM-RCV-50 BidCoS-RF`

But as I'm not using HomeMatic without IP as of yet I've deactivated this instance all together until needed.

After that it imported just fine.

Just still having issues with my docker installation of IOBroker where I've got to manually specify my ports in the URL because its behind a reverse proxy.

Is there a configuration for external ports if they're mapped through docker? I think this is related to #304

**Comment by zech** [comment]
![image](https://user-images.githubusercontent.com/460040/98303916-40b8ce80-1fbf-11eb-8cae-9e012d0824f8.png)

`10.10.0.1` is the IP of the docker host which maps it's own (real or external) ports to ports inside the container. I'd give `8082` and `8084` other external ports like `28082` and `28084` if I could specify them somewhere in configuration.

**Comment by Zefau** [comment]
I close this issue since it is solved. Let's move the discussion of the new issue to #304.
